service:
  name: monzo-penny-pot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 256

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
