service:
  name: monzo-penny-pot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:eu-west-2:*:*

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: post
          path: webhook
  login:
    handler: handler.login
    events:
      - http:
          method: get
          path: login
  setup:
    handler: handler.setup
    events:
      - http:
          method: post
          path: setup
